name: CC - Build UI
description: Build the UI code of CC

on:
    workflow_dispatch: ~
    push:
        branches:
        - 'care-connect'
        - 'care-connect-develop'
        paths:
        - '**frontend/**'
    pull_request:
        branches:
        - 'care-connect'
        - 'care-connect-develop'
        paths:
        - '**frontend/**'
        

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.5' 

    - name: Install dependencies
      working-directory: ./careconnect2025/frontend
      run: flutter pub get

    - name: Build Flutter Web
      working-directory: ./careconnect2025/frontend
      run: flutter build web --base-href "/"
      env: 
          CC_BASE_URL_WEB: https://2hzh4p0ug6.execute-api.us-east-1.amazonaws.com
          DEEPSEEK_API_KEY: ""
          OPENAI_API_KEY: ""
          FITBIT_CLIENT_SECRET: ""
          FITBIT_CLIENT_ID: ""

    
    - name: Set environment variables
      run: |
        echo "ZIP_NAME=cc-web-${GITHUB_SHA::7}-$(date +%Y%m%d).zip" >> $GITHUB_ENV


    - name: Zip Web Build
      working-directory: ./careconnect2025/frontend
      run: |
        cd build/web
        zip -r "../$ZIP_NAME" .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAZKYPD2ZB74YL5WVG
        aws-secret-access-key: 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
        aws-region: us-east-1

    - name: Upload to S3
      working-directory: ./careconnect2025/frontend
      run: |
        ls
        cd build/web
        aws s3 cp build/$ZIP_NAME s3://cc-iac-us-east-1-${{secrets.AWS_ACCOUNT_ID}}/cc-backend-builds/$ZIP_NAME
