name: CI - CC Spring Boot Backend

on:
  workflow_dispatch: ~
  push:
    branches:
      - 'care-connect'
      - 'care-connect-develop'
    paths:
      - '**backend/**'
  pull_request:
    branches:
      - 'care-connect'
      - 'care-connect-develop'
    paths:
      - '**backend/**'

jobs:
  build-all:
    environment: aws
    runs-on: ubuntu-latest
    concurrency: 
      group: 'ci-cc-backend-${{ github.ref }}'
    steps:
      - name: Check out
        id: checkout
        uses: actions/checkout@v4
      - name: Local CI
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.service == 'core'
        uses: ./careconnect2025/backend/core/github/actions/ci
      
  create-release:
    runs-on: ubuntu-latest
    needs: build-all
    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/develop')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@latest
        with:
          tag_name: cc-v${{ github.run_number }}
          release_name: CC-B R-v${{ github.run_number }}
          body_path: ./backend/core/target/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
