
name: CC - Push to AWS S3

on:
  release:
    types: [ published ]

env:
  AWS_REGION: us-east-1

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: aws

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    
    - name: Download release asset
      uses: actions/github-release-download@v1
      with:
        repo: ${{ github.repository }}
        tag: ${{ github.event.release.tag_name }}
        file: cc-core-b-for-lambda-v${{ github.run_number }}.zip

    - name: List
      run: pwd && ls
      
    - name: Upload to S3
      run: aws s3 cp target/my-app.zip s3://cc-iac-us-east-1-641592448579/cc-backend-builds/cc-core-b-for-lambda-v${{ github.run_number }}.zip
      

